---
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

resources:
- name: infra-integrator
  type: terraform
  source:
    storage:
      bucket: tax-aws-infrastructure
      bucket_path: integrator/
      region_name: eu-west-1
      access_key_id: {{storage_aws_access_key}}
      secret_access_key: {{storage_aws_secret_key}}
    # the '//' indicates a sub-directory in a git repo
    terraform_source: github.com/dhrapson/tax-aws-infrastructure//integrator
    vars:
      tag_name: concourse

- name: infra-client
  type: terraform
  source:
    storage:
      bucket: tax-aws-infrastructure
      bucket_path: client/
      region_name: eu-west-1
      access_key_id: {{storage_aws_access_key}}
      secret_access_key: {{storage_aws_secret_key}}
    # the '//' indicates a sub-directory in a git repo
    terraform_source: github.com/dhrapson/tax-aws-infrastructure//client
    vars:
      tag_name: concourse

- name: tax-secrets
  type: git
  source:
    uri: git@bitbucket.org:dhrapson/tax-secrets.git
    branch: master
    private_key: {{private_key}}

jobs:
- name: infra-integrator-plan
  plan:
    - get: tax-secrets
      trigger: true
    - put: infra-integrator
      params:
        env_name: dhr
        plan_only: true
        var_file: tax-secrets/dhr-credentials.yml

- name: infra-integrator-apply
  plan:
    - get: infra-integrator
      trigger: true
      passed: [infra-integrator-plan]
    - get: tax-secrets
      trigger: false
    - put: infra-integrator
      params:
        env_name: dhr
        plan_run: true
        var_file: tax-secrets/dhr-credentials.yml

- name: infra-client-plan
  plan:
    - get: tax-secrets
      trigger: true
      passed: [infra-integrator-apply]
    - put: infra-client
      params:
        env_name: dhr
        plan_only: true
        var_file: tax-secrets/dhr-credentials.yml

- name: infra-client-apply
  plan:
    - get: infra-client
      trigger: true
      passed: [infra-client-plan]
    - get: tax-secrets
      trigger: false
    - put: infra-client
      params:
        env_name: dhr
        plan_run: true
        var_file: tax-secrets/dhr-credentials.yml
